services:
    one-todo:
        container_name: one-todo
        build:
            context: .
        ports:
            - "127.0.0.1:3000:3000"
        restart: always
        extra_hosts:    
            - "host.docker.internal:host-gateway"