//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(column_type = "Text")]
    pub avatar: String,
    #[sea_orm(column_type = "Text")]
    pub google_access_token: String,
    #[sea_orm(column_type = "Text")]
    pub google_refresh_token: String,
    pub has_google_calendar_access: i8,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_subscriptions::Entity")]
    UserSubscriptions,
}

impl Related<super::user_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSubscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
